// Server-side GeoJSON access. The data file is static and generated by
// scripts/fetch-data.mjs; we read it from disk for SEO country pages and
// counts. The client map fetches /data/points.geojson directly.
import { readFile } from "node:fs/promises";
import { join } from "node:path";

let cache = null;

export async function loadGeo() {
  if (cache) return cache;
  try {
    const p = join(process.cwd(), "public", "data", "points.geojson");
    const raw = await readFile(p, "utf8");
    cache = JSON.parse(raw);
  } catch {
    cache = { type: "FeatureCollection", features: [] };
  }
  return cache;
}

export function countrySlug(name) {
  return String(name)
    .toLowerCase()
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export async function listCountries() {
  const geo = await loadGeo();
  const map = new Map();
  for (const f of geo.features) {
    const c = f.properties && f.properties.country;
    if (!c) continue;
    const slug = countrySlug(c);
    const cur = map.get(slug) || { name: c, slug, count: 0 };
    cur.count += 1;
    map.set(slug, cur);
  }
  return [...map.values()].sort((a, b) => b.count - a.count);
}

export async function countryBySlug(slug) {
  const geo = await loadGeo();
  const features = geo.features.filter(
    (f) =>
      f.properties &&
      f.properties.country &&
      countrySlug(f.properties.country) === slug
  );
  if (!features.length) return null;
  return {
    name: features[0].properties.country,
    slug,
    count: features.length,
    features,
  };
}
